<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="MotusPhysics.Core">
        <HintPath>Motus\MotusPhysics.Core.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
